### PR TITLE
added Contributing Guidelines

### PR DESCRIPTION
**Pull request by stefan2904**
maybe, maybe not. :)

### CODE REVIEW

**Review by PeterTheOne — APPROVED** [review]

**Comment by PeterTheOne** [comment]
Thanks for contributing. :+1:

Please also add that Logos need to be 400px wide.

What do you think about also adding the Contributing Guidelines to the README?

**Comment by stefan2904** [comment]
> Please also add that Logos need to be 400px wide.

--> "Allow edits from maintainers." is set to true. :)

> What do you think about also adding the Contributing Guidelines to the README?

--> https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by PeterTheOne** [comment]
I'm not a maintainer. :(

**Comment by PublicScam** [comment]
This is great, thanks a lot.

**Pull request merged**
