### PR TITLE
profile images: add inner border radius

### PR DESCRIPTION
**Pull request by PeterTheOne**
old:
screenshot_2017-03-09_12-57-45
new:
screenshot_2017-03-09_12-58-37

### CODE REVIEW

**Comment by sqrt2** [comment]
I was just about to write about those other profile classes :) Thanks.

**Comment by PeterTheOne** [comment]
@sqrt2 are there more "todos" written somewhere?

**Comment by sqrt2** [comment]
@PeterTheOne I'm not quite sure which list you've been looking at, to be honest. There's a pad with some more suggestions if you want to take a look.

**Comment by eest9** [comment]
I've sent him a link to the Issues Pad.

**Pull request merged**
