### PR TITLE
randomize representatives

### PR DESCRIPTION
**Pull request by PeterTheOne**

### CODE REVIEW

**Comment by PublicScam** [comment]
The intention was to have the list ordered by name, because users can't search for them directly.

**Comment by eest9** [comment]
We should discuss this.
I'm sure people at the beginning from the list get contacted more often than at the end.

**Comment by PeterTheOne** [comment]
You can search with in browser search `Ctrl/Cmd + f`, but if that is the issue we could implement a seach field.

**Comment by PublicScam** [comment]
@eest9 No doubt, but randomizing the list would kill any kind of structure.
@PeterTheOne Yes, the ultimate goal is a (properly implemented) search field. `Ctrl + f` does not meet our user-friendliness quality standards.

**Pull request merged**
