### PR TITLE
Sobotka

### PR DESCRIPTION
**Pull request by eest9**
BM Sobotka doesn't have a twitter account. The formaly listed account is a satire account.

### CODE REVIEW

**Comment by PublicScam** [comment]
@socialhack Please approve cada165.

**Comment by PublicScam** [comment]
@eest9 I was told by @socialhack brandstetter needs to be advertized as oevp associate.

**Comment by eest9** [comment]
Yea brandstetter as oevp is okay because he is a CV member. But the twitter handle of Sobotka is still false.

**Comment by PublicScam** [comment]
Right. Please apply adjustments and I'll merge. Thanks!

**Pull request closed without merging**
