### PR TITLE
add mobile share links: fb-messenger, telegram, whatsapp (Beta)

### PR DESCRIPTION
**Pull request by PeterTheOne**

### CODE REVIEW

**Comment by PeterTheOne** [comment]
screenshot_2017-03-09_11-09-58
screenshot_2017-03-09_11-10-30
screenshot_2017-03-09_11-10-52

**Comment by PeterTheOne** [comment]
We could also change the share texts from 

> Stoppt das Überwachungspaket!

to

> Schau dir das an!

**Comment by PublicScam** [comment]
@socialhack Please approve.

**Comment by PeterTheOne** [comment]
#6 describes what I implemented here..

**Comment by socialhack** [comment]
changing the share text, approved. 

more share functions, approved. 

other questions?

**Comment by PublicScam** [comment]
@PeterTheOne I'm about to merge this commit. Is there any reason you included the wiki link to the SVG in our includes? The picture is public domain as far as licensing is concerned.

**Comment by PeterTheOne** [comment]
@PublicScam There should not be licensing concerns, but I linked it anyway.

**Comment by socialhack** [comment]
This looks good. Are there open issues preventing us from merge?

**Comment by PeterTheOne** [comment]
Nope, please merge @PublicScam :)

**Comment by PublicScam** [comment]
This is now merged into master branch.
@PeterTheOne Any clue why the hover effect doesn't work on the new icons?

**Comment by sqrt2** [comment]
Unlike the other icons, the new ones are not glyphs in a font, but SVG images. In order to get a hover effect, you need another version of these icons in red colour and corresponding style changes for the buttons.

**Comment by PeterTheOne** [comment]
@PublicScam Only the fb-messenger one is not a glyph because there is no font-awesome glyph for it. I will fix the hover effect.

**Comment by PeterTheOne** [comment]
see: #34

**Pull request merged**
